<template>
  <div class="min-h-screen bg-blue-pale">
    <div class="max-w-4xl mx-auto px-4 py-12">
      <div class="mb-6">
        <NuxtLink to="/" class="flex items-center text-gray-400 hover:text-gray-200">
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back
        </NuxtLink>
      </div>

      <h1 class="text-3xl font-bold mb-8 text-white">Disclaimer</h1>
      <p class="text-gray-300 mb-8">Effective Date: June 25, 2025</p>
      
      <div class="space-y-6 text-white">
        <section>
          <h2 class="text-xl font-semibold mb-4">1. Service Accuracy</h2>
          <p>While Veo3 strives to provide high-quality AI-powered video generation services, we cannot guarantee that:</p>
          <ul class="list-disc pl-6 mt-2">
            <li>Generated videos will exactly match your expectations or requirements</li>
            <li>The AI models will interpret your text prompts or images exactly as intended</li>
            <li>The output quality will be consistent across all generations</li>
            <li>The service will be error-free or uninterrupted</li>
          </ul>
        </section>

        <section>
          <h2 class="text-xl font-semibold mb-4">2. Technical Limitations</h2>
          <p>Users should be aware of the following technical constraints:</p>
          <ul class="list-disc pl-6 mt-2">
            <li>Video output is fixed at 1080p resolution and 8 seconds duration</li>
            <li>Image uploads are limited to JPG/JPEG/PNG formats under 10MB</li>
            <li>Fast model only supports text-to-video generation</li>
            <li>Processing times may vary based on server load and complexity</li>
            <li>Only one image can be processed at a time</li>
          </ul>
        </section>

        <section>
          <h2 class="text-xl font-semibold mb-4">3. Content Responsibility</h2>
          <p>Users are solely responsible for:</p>
          <ul class="list-disc pl-6 mt-2">
            <li>The legality and appropriateness of uploaded content</li>
            <li>Ensuring they have necessary rights to use uploaded images</li>
            <li>The use and distribution of generated videos</li>
            <li>Compliance with local laws and regulations</li>
          </ul>
        </section>

        <section>
          <h2 class="text-xl font-semibold mb-4">4. No Warranty</h2>
          <p>The service is provided "as is" without warranties of any kind, whether express or implied. Veo3 specifically disclaims any implied warranties of:</p>
          <ul class="list-disc pl-6 mt-2">
            <li>Merchantability</li>
            <li>Fitness for a particular purpose</li>
            <li>Non-infringement</li>
            <li>Accuracy of results</li>
          </ul>
        </section>

        <section>
          <h2 class="text-xl font-semibold mb-4">5. Limitation of Liability</h2>
          <p>Veo3 shall not be liable for:</p>
          <ul class="list-disc pl-6 mt-2">
            <li>Any direct, indirect, or consequential damages</li>
            <li>Loss of data or content during processing</li>
            <li>Service interruptions or technical failures</li>
            <li>Quality issues in generated videos</li>
          </ul>
        </section>

        <section>
          <h2 class="text-xl font-semibold mb-4">6. Third-Party Content</h2>
          <p>We are not responsible for any third-party content used in or generated by our service. Users must ensure they have appropriate rights for any third-party content they upload.</p>
        </section>

        <section>
          <h2 class="text-xl font-semibold mb-4">7. Contact Information</h2>
          <p>For questions about this disclaimer, please contact us at: support@vidveo3.com</p>
        </section>

        <section class="mt-8">
          <p class="text-sm">Last updated: {{ new Date().toLocaleDateString() }}</p>
        </section>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useSeo } from '~/composables/useSeo';

// @ts-ignore: Nuxt宏函数
definePageMeta({
  layout: false,
  name: 'disclaimer'
})

useSeo({
  title: 'AI Image Animator | Disclaimer',
  description: 'Read our disclaimer for AI Image Animator, including AI technology limitations, content responsibility, intellectual property, and other important terms.'
})
</script>

<style>
body {
  background-color: #111827; /* bg-blue-pale */
  color: #F3F4F6; /* text-gray-100 */
}
</style> 